--DROP TABLE mpa CASCADE;
--DROP TABLE genre CASCADE;
--DROP TABLE users CASCADE;
--DROP TABLE film CASCADE;
--DROP TABLE user_friend CASCADE;
--DROP TABLE film_like CASCADE;
--DROP TABLE film_genre CASCADE;

CREATE TABLE IF NOT EXISTS mpa (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    rating VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS genre (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    login VARCHAR(20) NOT NULL,
    name VARCHAR(50) NOT NULL,
    birthday DATE
);

CREATE TABLE IF NOT EXISTS film (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(200),
    releaseDate DATE DEFAULT NOT NULL,
    duration INTEGER NOT NULL,
    rating BIGINT NOT NULL REFERENCES mpa(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_friend (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    friend_id BIGINT NOT NULL REFERENCES users(id),
    approved BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS film_like (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    film_id BIGINT NOT NULL REFERENCES film(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS film_genre (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    film_id BIGINT NOT NULL REFERENCES film(id) ON DELETE CASCADE,
    genre_id BIGINT NOT NULL REFERENCES genre(id) ON DELETE CASCADE
);
